import crypto from 'node:crypto';
import { readStore, writeStore } from '../services/store.js';
import { getQuote } from '../services/marketDataService.js';
export async function getAlerts(req,res){const db=await readStore();res.json(db.alerts.filter(x=>x.userId===req.user.id));}
export async function addAlert(req,res){const {symbol,type,threshold,enabled=true}=req.body;if(!symbol||!type||threshold===undefined)return res.status(400).json({error:'Stock, alert type, and threshold are required.'});const db=await readStore();const a={id:crypto.randomUUID(),userId:req.user.id,symbol:symbol.toUpperCase(),type,threshold:Number(threshold),enabled:Boolean(enabled),createdAt:new Date().toISOString()};db.alerts.push(a);await writeStore(db);res.status(201).json(a);}
export async function toggleAlert(req,res){const db=await readStore();const a=db.alerts.find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!a)return res.status(404).json({error:'Alert not found.'});a.enabled=Boolean(req.body.enabled);await writeStore(db);res.json(a);}
export async function deleteAlert(req,res){const db=await readStore();db.alerts=db.alerts.filter(x=>!(x.id===req.params.id&&x.userId===req.user.id));await writeStore(db);res.status(204).end();}
export async function getPortfolio(req,res){const db=await readStore();const scenario=db.scenarios[req.user.id]||'rise';let holdings=db.holdings.filter(x=>x.userId===req.user.id);const demo=holdings.length===0;if(demo)holdings=[{id:'demo-nvda',symbol:'NVDA',shares:12,averagePrice:166.4},{id:'demo-aapl',symbol:'AAPL',shares:18,averagePrice:228.1},{id:'demo-msft',symbol:'MSFT',shares:8,averagePrice:481.25}];holdings=holdings.map(h=>{const q=getQuote(h.symbol,scenario);return {...h,currentPrice:q?.price||h.averagePrice,value:+((q?.price||h.averagePrice)*h.shares).toFixed(2),gain:+(((q?.price||h.averagePrice)-h.averagePrice)*h.shares).toFixed(2)};});res.json({holdings,total:holdings.reduce((s,h)=>s+h.value,0),gain:holdings.reduce((s,h)=>s+h.gain,0),demo});}
export async function addHolding(req,res){const {symbol,shares,averagePrice}=req.body;if(!symbol||!shares||!averagePrice)return res.status(400).json({error:'Stock, shares, and average price are required.'});const db=await readStore();const h={id:crypto.randomUUID(),userId:req.user.id,symbol:symbol.toUpperCase(),shares:Number(shares),averagePrice:Number(averagePrice)};db.holdings.push(h);await writeStore(db);res.status(201).json(h);}
export async function preferences(req,res){const db=await readStore();if(req.method==='GET')return res.json(db.preferences[req.user.id]||{notifications:true,darkMode:true,demoMode:true});db.preferences[req.user.id]={...(db.preferences[req.user.id]||{}),...req.body};await writeStore(db);res.json(db.preferences[req.user.id]);}
